### ISSUE TITLE
componentTitle not updated when using useState hook

### ISSUE THREAD

**Issue by huberv** [Silind/create-react-web-component#4]
Hi,
I just started tinkering with create-react-web-component. I used create-react-web-component to create a new web component "web-component" without adjusting anything in the created component.

I then copied over the bundle.js to an app I created with create-react-app.

In the "host" app I added a <script src="%PUBLIC_URL%/bundle.js"></script> to the public/index.html and I adjusted the the host App component to be like shown in this gist: https://gist.github.com/huberv/9ac6264239448e58e0f80690aaf40507

The initial rendering of the web component works fine and shows the correct title. However, when clicking the "toggle title"-button, the web component's title is not updated. I'm a bit stumped why.

**Comment by SimonHoiberg** [comment]
Hi @huberv 

Thank you for creating this issue - I've been able to reproduce the situation from your description, and I get the same problem. 
This is a bug - the web component should, of course, update when the attribute changes.

Nice catch :+1: I'll make a new release with a fix, as soon as I find the problem.

**Comment by SimonHoiberg** [comment]
:heavy_check_mark: This issue has been resolved.

If you update to version `2.0.14` of create-react-web-component, you should get the intended behavior using useState hook :slightly_smiling_face: 

Thank you for bringing this to my attention.

**Comment by huberv** [comment]
Hi Simon, 
Thanks for the swift fix, retested successfully!
Kind regards,
Valentin
